# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-18 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('avatar', models.CharField(max_length=100, verbose_name='头像路径')),
                ('bio', models.CharField(max_length=500, verbose_name='个人简历')),
            ],
            options={
                'db_table': 'blog_user',
            },
        ),
    ]
