# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-19 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_articlepost_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media/%Y%m%d/', verbose_name='标题图'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='total_views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
