# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-19 16:14
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200419_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(upload_to='article/%Y%m%d', verbose_name='标题图'),
        ),
    ]
