# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-20 01:50
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20200420_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(upload_to='static/media/%Y%m%d', verbose_name='标题图'),
        ),
    ]
