# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-20 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20200420_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='avatar',
        ),
    ]
